Repository yevhen-turovets/homepage, pull requests merged in 2020-05, with the labels that each got.

#3 First release to production
  README.md
  index.html
Labels: assignees, labels, milestones, projects, reviewers

#8 Add base.css stylesheet link
  index.html
Labels: enhancement

#14 Add primary information (closes #12 )
  index.html
Labels: enhancement

#15 Add secondary infrormation (closes #13 )
  index.html
Labels: enhancement

#16 Add content
  index.html
Labels: enhancement

#17 Release to production
  index.html
Labels: release

#28 Add personal informations (closes #26 )
  assets/images/avatar.svg
  index.html
Labels: enhancement

#32 Fix body bags (closes #27 )
  IMG_1284.PNG
  assets/stylesheets/base.css
  index.html
Labels: bug

#33 Create UA version site (closes #30 )
  uk-ua/index.html
Labels: enhancement

#35 Release version 1.0
  assets/.DS_Store
  assets/images/avatar.svg
  assets/stylesheets/base.css
  favicon.ico
  index.html
  ru-ru/index.html
  uk-ua/index.html
Labels: New release

#36 Some trouble with link
  index.html
  ru-ru/index.html
  uk-ua/index.html
Labels: bug

#38 Error from robot
  index.html
  ru-ru/index.html
  sw.js
  sw.js.map
  uk-ua/index.html
  workbox-c692813c.js
  workbox-c692813c.js.map
  workbox-config.js
Labels: bug

#39 Fix/homepage
  assets/stylesheets/base.css
  index.html
  ru-ru/index.html
  sw.js
  sw.js.map
  uk-ua/index.html
Labels: bug

#40 Add travis
  .travis.yml
Labels: New release

#41 New release
  .travis.yml
  assets/stylesheets/base.css
  index.html
  ru-ru/index.html
  sw.js
  sw.js.map
  uk-ua/index.html
Labels: New release

#42 Add integration with Zeit
  now.json
  sw.js.map
Labels: new integrations

#44 V2/update/texttranslation
  index.html
  ru-ru/index.html
  sw.js
  sw.js.map
  uk-ua/index.html
Labels: update text

#47 Fix languages link
  index.html
  ru-ru/index.html
  sw.js
  sw.js.map
  uk-ua/index.html
Labels: bug

#48 V2/feature/progressbar
  assets/stylesheets/style.css
  index.html
  sw.js
  sw.js.map
Labels: enhancement

#50 V2/feature/photogallary
  assets/photos/1-min.JPG
  assets/photos/10-min.JPG
  assets/photos/11-min.JPG
  assets/photos/2-min.JPG
  assets/photos/3-min.JPG
  assets/photos/4-min.JPG
  assets/photos/5-min.JPG
  assets/photos/6-min.JPG
  assets/photos/7-min.JPG
  assets/photos/8-min.JPG
  assets/photos/9-min.JPG
  index.html
  sw.js
  sw.js.map
Labels: enhancement

#52 Udate language version
  index.html
  ru-ru/index.html
  sw.js
  sw.js.map
  uk-ua/index.html
Labels: fix

#53 V2/fix/css
  assets/stylesheets/style.css
  index.html
  ru-ru/index.html
  sw.js
  sw.js.map
  uk-ua/index.html
Labels: fix

#54 New release version 3 (closes #51 )
  JOKE.md
  README.md
  assets/photos/1-min.JPG
  assets/photos/10-min.JPG
  assets/photos/11-min.JPG
  assets/photos/2-min.JPG
  assets/photos/3-min.JPG
  assets/photos/4-min.JPG
  assets/photos/5-min.JPG
  assets/photos/6-min.JPG
  assets/photos/7-min.JPG
  assets/photos/8-min.JPG
  assets/photos/9-min.JPG
  assets/photos/kolomo.JPG
  assets/stylesheets/style.css
  index.html
  now.json
  ru-ru/index.html
  sw.js
  sw.js.map
  uk-ua/index.html
Labels: New release
